
FROM ruby:3.2.2-slim

WORKDIR /rails

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  libpq-dev \
  curl \
  libvips \
  postgresql-client \
  ffmpeg


COPY Gemfile Gemfile.lock ./

RUN bundle install

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000

