services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    command: sh -c "bundle exec foreman start -f Procfile.dev"
    restart: always
    volumes:
      - .:/rails:cached
      - app-storage:/rails/storage
    ports:
      - "3002:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/prova_development
      - REDIS_URL=redis://redis:6379/1

  postgres:
    image: postgres:14.2
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prova_development
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: {}
  app-storage: {}