
FROM ruby:3.4.10-slim

WORKDIR /rails

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  libpq-dev \
  libyaml-dev \
  pkg-config \
  curl \
  libjemalloc2 \
  libvips \
  postgresql-client \
  ffmpeg \
  ghostscript \
  poppler-utils \
  tesseract-ocr \
  tesseract-ocr-ita && \
  apt-get install libncurses5-dev libncursesw5-dev -y && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives


COPY Gemfile Gemfile.lock ./

RUN bundle install

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000

