
FROM ruby:3.2.2-slim

WORKDIR /rails

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  git \
  libpq-dev \
  curl \
  libjemalloc2 \
  libvips \
  postgresql-client \
  ffmpeg && \
  apt-get install watchman libncurses5-dev libncursesw5-dev -y && \
  rm -rf /var/lib/apt/lists /var/cache/apt/archives


COPY Gemfile Gemfile.lock ./

RUN bundle install

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000

