default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: prova_production
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: prova_development
  username: prova
  password: ptaxptax
  port: 5433

test:
  <<: *default
  # Force test to use a separate database, ignoring DATABASE_URL
  url: <%= ENV.fetch('TEST_DATABASE_URL', "postgresql://#{ENV.fetch('POSTGRES_USER', 'prova')}:#{ENV.fetch('POSTGRES_PASSWORD', 'ptaxptax')}@#{ENV.fetch('POSTGRES_HOST', 'db')}:5432/prova_test") %>
