default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: prova_production
  username: prova
  password: ptaxptax
  host: db
  port: 5432

development:
  <<: *default
  database: prova_development
  username: postgres
  password: postgres
  port: 5433

test:
  <<: *default
  database: prova_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: 5432
