default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  # host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432

production:
  <<: *default
  database: prova_production
  username: prova
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>

development:
  <<: *default
  database: prova_development
  username: paolotax
  password: ptaxptax

test:
  <<: *default
  database: prova_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>


# production:
#   <<: *default
#   database: <%= ENV['POSTGRES_DB'] %>
#   username: <%= ENV['POSTGRES_USER'] %>
#   password: <%= ENV['POSTGRES_PASSWORD'] %>
#   host: <%= ENV['POSTGRES_HOST'] %>
#   # port: 5432

