service: prova

image: paolotax/prova

servers:
  web:
    - 159.69.18.62

  job:
    hosts:
      - 159.69.18.62
    cmd: bundle exec sidekiq -q default -q mailers -q ahoy

# Credentials for your image host.
registry:
  username: paolotax

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD


builder:
  arch: amd64

proxy:
  ssl: true
  host: app.paolotax.it www.paolotax.it

# Use accessory services (secrets come from .env).

accessories:
  db:
    image: postgres:15
    host: 159.69.18.62
    port: 5432
    env:
      clear:
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_DB: POSTGRES_DB
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    host: 159.69.18.62
    directories:
      - data:/data
