service: prova

image: paolotax/prova

servers:
  web:
    - 159.69.18.62
  job:
    hosts:
      - 159.69.18.62
    cmd: bundle exec sidekiq -q default -q mailers -q ahoy

registry:
  username: paolotax
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

proxy:
  ssl: true
  host: paolotax.it

env:
  clear:
    POSTGRES_USER: prova
    POSTGRES_DB: prova_production
    POSTGRES_PASSWORD: ptaxptax
  secret:
    - RAILS_MASTER_KEY

accessories:
  db:
    image: postgres:15
    host: 159.69.18.62
    port: 5432:5432
    env:
      clear:
        POSTGRES_USER: prova
        POSTGRES_DB: prova_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    host: 159.69.18.62
    directories:
      - data:/data
