service: prova

image: paolotax/prova

servers:
  web:
    hosts:
      - 159.69.18.62
  job:
    hosts:
      - 159.69.18.62
    cmd: bundle exec sidekiq -q default -q mailers -q ahoy

registry:
  username: paolotax
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch:
    - amd64

proxy:
  ssl: true
  host: paolotax.it
  app_port: 3000


env:
  clear:
    HOST: paolotax.it
    RAILS_SERVE_STATIC_FILES: "true"
    RAILS_LOG_TO_STDOUT: "true"
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - REDIS_URL


# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

accessories:
  db:
    image: postgres:15
    host: 159.69.18.62
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: prova
        POSTGRES_DB: prova_production
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql

  redis:
    image: redis:latest
    host: 159.69.18.62
    port: "127.0.0.1:6379:6379"
    directories:
      - data:/data
