service: prova-staging

image: paolotax/prova-staging

servers:
  web:
    hosts:
      - 116.203.224.90
    labels:
      thruster.http.routers.prova-staging.entrypoints: websecure
      thruster.http.routers.prova-staging.rule: Host("scagnozz.com")
      thruster.http.routers.prova-staging.tls.certresolver: letsencrypt
    options:
      network: "private"
  job:
    hosts:
      - 116.203.224.90
    cmd: bundle exec sidekiq -q default -q mailers -q ahoy
    options:
      network: "private"

registry:
  username: paolotax

  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
  clear:
    DB_HOST: 116.203.224.90
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    REDIS_URL: "redis://prova-redis:6379/0"
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - TURNSTILE_SITE_KEY
    - TURNSTILE_SECRET_KEY
    - OPENAI_ACCESS_TOKEN

thruster:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    network: "private"
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    entryPoints.web.http.redirections.entryPoint.to: websecure
    entryPoints.web.http.redirections.entryPoint.scheme: https
    entryPoints.web.http.redirections.entrypoint.permanent: true
    certificatesResolvers.letsencrypt.acme.email: "paolo.tassinari@hey.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

builder:
  args:
    RUBY_VERSION: 3.2.2
  remote:
    arch: amd64

accessories:
  db:
    image: postgres:15
    host: 116.203.224.90
    port: 5432
    env:
      clear:
        POSTGRES_USER: POSTGRES_USER
        POSTGRES_DB: POSTGRES_DB
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/staging.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
    options:
      network: "private"
  redis:
    image: redis:latest
    host: 116.203.224.90
    directories:
      - data:/data
    options:
      network: "private"
