service: prova

image: paolotax/prova

servers:
  web:
    - 159.69.18.62
  job:
    hosts:
      - 159.69.18.62
    cmd: bundle exec sidekiq -q default -q mailers -q ahoy

registry:
  username: paolotax
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

proxy:
  ssl: true
  host: paolotax.it

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL

accessories:
  db:
    image: postgres:15
    host: 159.69.18.62
    port: "127.0.0.1:5432:5432"
    env:
      clear:
        POSTGRES_USER: prova
        POSTGRES_DB: prova_production
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        POSTGRES_PASSWORD: ptaxptax
      # secret:
      #   - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql


  redis:
    image: redis:latest
    host: 159.69.18.62
    directories:
      - data:/data
