service: prova-staging
image: paolotax/prova-staging

servers:
  web:
    hosts:
      - 116.203.224.90
    options:
      publish:
        - "81:3000"
      network: "private"

  job:
    hosts:
      - 116.203.224.90
    cmd: bundle exec sidekiq -q default -q mailers -q ahoy
    options:
      network: "private"

registry:
  username: paolotax
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: staging
    DB_HOST: 116.203.224.90
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    REDIS_URL: "redis://prova-staging-redis:6379/0"
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - TURNSTILE_SITE_KEY
    - TURNSTILE_SECRET_KEY
    - OPENAI_ACCESS_TOKEN

builder:
  args:
    RUBY_VERSION: 3.2.2
  remote:
    arch: amd64

accessories:
  db:
    image: postgres:15
    host: 116.203.224.90
    port: 5433
    env:
      clear:
        POSTGRES_USER: STAGING_USER
        POSTGRES_DB: STAGING_DB
      secret:
        - POSTGRES_PASSWORD
    files:
      - db/staging.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - staging_data:/var/lib/postgresql/data
    options:
      network: "private"

  redis:
    image: redis:latest
    host: 116.203.224.90
    directories:
      - data:/data
    options:
      network: "private"
