:concurrency: 5
:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    adozioni_scraper:
      cron: '0 */6 * * *'  # Esegue ogni 6 ore
      class: AdozioniScraperJob
      queue: default
      unique: true
