:concurrency: 5
:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    adozioni_scraper:
      cron: '0 */6 * * *'  # Esegue ogni 6 ore
      class: AdozioniScraperJob
      queue: default
      unique: true

    clean_orphaned_righe:
      cron: '0 3 1 * *'  # Esegue il 1° di ogni mese alle 3:00 AM
      class: CleanOrphanedRigheJob
      queue: default
      unique: true
      description: 'Pulisce le righe orfane (senza DocumentoRiga) e salva un backup in tmp/'
