class CreateMiurTables < ActiveRecord::Migration[8.1]
  ANNI = %w[202425 202526 202627].freeze

  def up
    execute <<~SQL
      CREATE TABLE miur_adozioni (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        anno_scolastico varchar NOT NULL,
        annocorso varchar, autori varchar, codiceisbn varchar, codicescuola varchar,
        combinazione varchar, consigliato varchar, daacquist varchar, disciplina varchar,
        editore varchar, nuovaadoz varchar, prezzo varchar, sezioneanno varchar,
        sottotitolo varchar, tipogradoscuola varchar, titolo varchar, volume varchar,
        import_scuola_id bigint,
        PRIMARY KEY (anno_scolastico, id)
      ) PARTITION BY LIST (anno_scolastico)
    SQL
    execute <<~SQL
      CREATE UNIQUE INDEX index_miur_adozioni_on_classe ON miur_adozioni
        (anno_scolastico, codicescuola, annocorso, sezioneanno, combinazione, codiceisbn, disciplina)
    SQL
    execute "CREATE INDEX idx_miur_adoz_ee ON miur_adozioni (codicescuola) INCLUDE (editore, annocorso, disciplina) WHERE tipogradoscuola = 'EE'"
    execute "CREATE INDEX idx_miur_adozioni_codicescuola ON miur_adozioni (codicescuola)"
    execute "CREATE INDEX idx_miur_adozioni_disc_anno_tg ON miur_adozioni (disciplina, annocorso, tipogradoscuola)"

    execute <<~SQL
      CREATE TABLE miur_scuole (
        id bigint GENERATED BY DEFAULT AS IDENTITY,
        anno_scolastico varchar NOT NULL,
        area_geografica varchar, cap varchar, codice_comune varchar,
        codice_istituto_riferimento varchar, codice_scuola varchar, comune varchar,
        denominazione varchar, denominazione_istituto_riferimento varchar,
        descrizione_caratteristica varchar, email varchar,
        indicazione_sede_direttivo varchar, indicazione_sede_omnicomprensivo varchar,
        indirizzo varchar, pec varchar, provincia varchar, regione varchar,
        sede_scolastica varchar, sito_web varchar, tipo_scuola varchar,
        import_scuola_id bigint,
        PRIMARY KEY (anno_scolastico, id)
      ) PARTITION BY LIST (anno_scolastico)
    SQL
    execute "CREATE UNIQUE INDEX index_miur_scuole_on_codice_scuola ON miur_scuole (anno_scolastico, codice_scuola)"
    execute "CREATE INDEX idx_miur_scuole_cod ON miur_scuole (codice_scuola) INCLUDE (regione, provincia)"
    execute "CREATE INDEX idx_miur_scuole_tipo ON miur_scuole (tipo_scuola)"

    ANNI.each do |anno|
      execute "CREATE TABLE miur_adozioni_#{anno} PARTITION OF miur_adozioni FOR VALUES IN ('#{anno}')"
    end
    execute "CREATE TABLE miur_scuole_202627 PARTITION OF miur_scuole FOR VALUES IN ('202627')"

    create_table :miur_import_runs do |t|
      t.string :anno_scolastico, null: false
      t.string :dataset, null: false, default: "adozioni" # adozioni | scuole
      t.integer :righe_totali
      t.integer :delta_righe
      t.jsonb :regioni_aggiornate, default: []
      t.jsonb :regioni_stale, default: []
      t.jsonb :regioni_fallite, default: []
      t.datetime :completed_at
      t.timestamps
      t.index [:dataset, :completed_at]
    end
  end

  def down
    drop_table :miur_import_runs
    # CASCADE elimina silenziosamente anche gli oggetti dipendenti creati da
    # migration successive (matview, bridge view) in caso di rollback out-of-order.
    execute "DROP TABLE miur_adozioni CASCADE"
    execute "DROP TABLE miur_scuole CASCADE"
  end
end
